### ISSUE TITLE
Safari Cascadea Font Issue

### ISSUE THREAD

**Issue by vandermerwed** [vandermerwed/Roam-Research-Dark#1]
The Menlo font is not loading properly using Cascadea for Safari.
![image](https://user-images.githubusercontent.com/8472841/79418006-d2c1a100-7fb3-11ea-9f74-590b2b998a5b.png)

**Comment by mikefreuden** [comment]
Hey there, I'm actually the developer of Cascadea! I believe this is an issue on Cascadea's end rather than with this style. Cascadea 1.5.1 should be rolling out now on the App Store with a fix - please let me know if you have any trouble after updating and reinstalling this style.

**Comment by JasperGeh** [comment]
I was actually the one complaining to vandermerwed :) 
The update fixed it! Thanks, Mike; money well spent!

**Comment by vandermerwed** [comment]
Thanks @mikefreuden and thanks @JasperGeh for confirming 👍
