### ISSUE TITLE
Remove markdown symbols for styles.

### ISSUE THREAD

**Issue by misalyogeshwar** [vandermerwed/Roam-Research-Dark#19]
When we are editing any block and want to make some text bold, italic etc. It should look like **'Bold'** Instead of **\*\*Bold\*\***

**Comment by misalyogeshwar** [comment]
This can be very important feature for people migrating from other note taking apps like Notion, evernote etc. and I am sure there will be plenty of them

**Comment by vandermerwed** [comment]
Hi @misalyogeshwar thanks so much for the feedback!

Just want to make sure I understand what you are referring to. Do you mean these?
![image](https://user-images.githubusercontent.com/8472841/84577405-1ff79e80-adbc-11ea-9e8e-7511960507ef.png)

If so then unfortunately there's nothing I can do about this. This is the way Roam renders the text. Without any wrapping elements around those specific characters (e.g: `*`) I can't style them unfortunately 😞
