### ISSUE TITLE
Typefaces, pill-styled tags and line wrapping in autocomplete menus

### ISSUE THREAD

**Issue by JasperGeh** [vandermerwed/Roam-Research-Dark#3]
As the title suggests.
- Inclusion of some pretty typefaces (if possible/feasible given wide compatibility): Avenir, Raleway, Calendas Plus
- Pill-styled tags similar to picture below (Custom colours depending on selectable text/tag would be **ace** and the cherriest of cherries on top)
- Wrapping text in block-embed menus (Malcolm suggested a fix in the #css-themes channel)

![image](https://user-images.githubusercontent.com/28384742/79609327-d7db3900-80f6-11ea-9425-04dc006493f6.png)

**Comment by vandermerwed** [comment]
Thanks a lot @JasperGeh! I split this issue into individual issues so they can be worked on separately.

I'll be closing this issue now. Progress on the individual tickets can be tracked here: #4, #5, #6
